mod.id = "maparthelper"
mod.name = "Mapart Helper"
mod.group = "rh.maparthelper"
mod.version = "0.13.1-bp"
mod.fabric_loader = "0.18.4"
mod.version_type = "STABLE"

publish.modrinth = "qRKpqkGI"
publish.curseforge_id = "1343604"
publish.curseforge_slug = "mapart-helper"
publish.github_repo = "Redheris/Mapart-Helper"
publish.mod_icon_url = "https://cdn.modrinth.com/data/qRKpqkGI/31d2b319605a07e5b5565eece0e963e78bb92d30.png"
publish.announce_for = "none" # "none" if no announcement
publish.dry_run = "false"

["1.21.5"]
# Minecraft dependency for fabric.mod.json e.g. ">=1.21.6 <=1.21.8"
mc_dep = "1.21.5"
# Release title for Modrinth and Curseforge
release_title = "1.21.5"
# Space-separated compatible versions for publishing e.g. "1.21.8 1.21.11 26.1"
mc_targets = "1.21.5"
# Dependencies
fabric_api = "0.128.2+1.21.5"
yacl = "3.8.2+1.21.5-fabric"
modmenu = "14.0.0"
# Mappings
parchment = "1.21.5:2025.06.15"
mojbackward = "1.21.8+build.3"

["1.21.4"]
mc_dep = "1.21.4"
release_title = "1.21.4"
mc_targets = "1.21.4"
# Dependencies
fabric_api = "0.119.4+1.21.4"
yacl = "3.8.2+1.21.4-fabric"
modmenu = "13.0.2"
# Mappings
parchment = "1.21.4:2025.03.23"
mojbackward = "1.21.4+build.3"
