mod.id = "maparthelper"
mod.name = "Mapart Helper"
mod.group = "rh.maparthelper"
mod.version = "0.13.1"
mod.fabric_loader = "0.18.4"
mod.version_type = "STABLE"

publish.modrinth = "qRKpqkGI"
publish.curseforge_id = "1343604"
publish.curseforge_slug = "mapart-helper"
publish.github_repo = "Redheris/Mapart-Helper"
publish.mod_icon_url = "https://cdn.modrinth.com/data/qRKpqkGI/31d2b319605a07e5b5565eece0e963e78bb92d30.png"
publish.announce_for = "26.1" # "none" if no announcement
publish.dry_run = "false"

["1.21.8"]
# Minecraft dependency for fabric.mod.json e.g. ">=1.21.6 <=1.21.8"
mc_dep = "1.21.8"
# Release title for Modrinth and Curseforge
release_title = "1.21.8"
# Space-separated compatible versions for publishing e.g. "1.21.8 1.21.11 26.1"
mc_targets = "1.21.8"
# Dependencies
fabric_api = "0.136.1+1.21.8"
yacl = "3.8.2+1.21.6-fabric"
modmenu = "15.0.0"
# Mappings
parchment = "1.21.8:2025.09.14"
mojbackward = "1.21.8+build.3"

["1.21.11"]
mc_dep = "1.21.11"
release_title = "1.21.11"
mc_targets = "1.21.11"
# Dependencies
fabric_api = "0.141.3+1.21.11"
yacl = "3.8.2+1.21.11-fabric"
modmenu = "17.0.0-beta.2"
# Mappings
parchment = "1.21.11:2025.12.20"

["26.1"]
mc_dep = "26.1"
mc_dep_fabric = "~26.1"
release_title = "26.1"
mc_targets = "26.1"
# Dependencies
fabric_api = "0.144.3+26.1"
yacl = "3.9.1+26.1-fabric"
modmenu = "18.0.0-alpha.8"
